"use client"
import { useMemo, useState } from "react"
import { Star, ShoppingCart, Phone, FileText, Truck, Shield, Headphones } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { QuantitySelector } from "@/components/cart/quantity-selector"
import { formatEnglishPrice } from "@/lib/data"
import { useCart } from "@/lib/cart/cart-store"
import { storeContactConfig } from "@/lib/store-contact-config"
import { useContactInfo } from "@/components/site-settings-provider"
import type { ProductVariant } from "@/types/product"
interface ProductInfoProps { id:string; slug:string; name:string; brand:string; model:string; sku:string|null; rating:number; reviewCount:number; shortDescription:string; inStock:boolean; stockCount:number; warranty:string; price:number; oldPrice:number|null; discount:number|null; mainImageUrl:string|null; optionGroupTitle:string|null; variants:ProductVariant[] }
export function ProductInfo({id,slug,name,brand,model,sku,rating,reviewCount,shortDescription,inStock,stockCount,warranty,price,oldPrice,discount,mainImageUrl,optionGroupTitle,variants}:ProductInfoProps){
 const activeVariants=useMemo(()=>variants.filter(v=>v.isActive),[variants]); const[selectedVariantId,setSelectedVariantId]=useState(activeVariants[0]?.id??null); const selectedVariant=activeVariants.find(v=>v.id===selectedVariantId)??activeVariants[0]??null; const displayedPrice=selectedVariant?.price??price; const[quantity,setQuantity]=useState(1); const{addToCart}=useCart(); const contact=useContactInfo(); const supportPhone=contact.supportPhone||contact.mobile||storeContactConfig.mobile; const safeStockCount=typeof stockCount==="number"?stockCount:-1; const maxQuantity=safeStockCount>0?safeStockCount:99;
 const handleQuantityChange=(next:number)=>{if(safeStockCount>0&&next>safeStockCount){toast.warning("تعداد انتخاب‌شده بیشتر از موجودی انبار است");return}setQuantity(Math.max(1,next))};
 const handleAddToCart=()=>{if(!inStock){toast.error("این محصول در حال حاضر ناموجود است");return} if(activeVariants.length&&!selectedVariant){toast.error("ابتدا یکی از گزینه‌های محصول را انتخاب کنید");return} addToCart({productId:id,variantId:selectedVariant?.id??null,variantGroupTitle:selectedVariant?optionGroupTitle:null,variantLabel:selectedVariant?.label??null,slug,name,model,sku:selectedVariant?.sku??sku,brandName:brand,price:displayedPrice,oldPrice:selectedVariant?null:oldPrice,mainImageUrl,stockQuantity:safeStockCount},quantity)};
 return <div className="space-y-4 lg:space-y-3"><div className="flex items-center gap-2"><span className="text-sm text-muted-foreground">برند:</span><span className="text-sm font-medium text-primary">{brand}</span></div><h1 className="text-2xl font-bold leading-snug text-foreground md:text-3xl">{name}</h1><p className="text-muted-foreground" dir="ltr">{model}</p><div className="flex items-center gap-3"><div className="flex items-center gap-1">{[...Array(5)].map((_,i)=><Star key={i} className={`h-5 w-5 ${i<Math.floor(rating)?"fill-accent text-accent":"fill-muted text-muted"}`}/>)}</div><span className="font-medium">{rating}</span><span className="text-sm text-muted-foreground">({reviewCount} نظر)</span></div><p className="text-sm leading-6 text-muted-foreground md:text-base md:leading-7">{shortDescription}</p><div className="flex items-center gap-2">{inStock?<><span className="h-3 w-3 animate-pulse rounded-full bg-green-500"/><span className="font-medium text-green-600">موجود در انبار</span><span className="text-sm text-muted-foreground">({safeStockCount>0?safeStockCount.toLocaleString("en-US"):"قابل بررسی"} عدد)</span></>:<><span className="h-3 w-3 rounded-full bg-red-500"/><span className="font-medium text-red-600">ناموجود</span></>}</div><div className="flex items-center gap-2 text-sm"><Shield className="h-5 w-5 text-primary"/><span>{warranty}</span></div>
 {activeVariants.length?<div className="space-y-2 rounded-2xl border bg-card p-3"><p className="text-sm font-bold">انتخاب {optionGroupTitle||"گزینه"}</p><div className="flex flex-wrap gap-2">{activeVariants.map(v=><Button type="button" key={v.id} variant={selectedVariant?.id===v.id?"default":"outline"} className="rounded-xl" onClick={()=>setSelectedVariantId(v.id)}>{v.label}</Button>)}</div></div>:null}
 <div className="space-y-2 rounded-2xl bg-muted/50 p-3 md:p-4"><div className="flex items-center justify-between gap-3"><span className="text-muted-foreground">قیمت:</span>{discount&&!selectedVariant?<span className="rounded-lg bg-accent px-3 py-1 text-sm font-bold text-accent-foreground">{discount}٪ تخفیف</span>:null}</div><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div className="space-y-1"><div className="flex items-baseline gap-2"><span className="text-3xl font-bold text-foreground">{formatEnglishPrice(displayedPrice)}</span><span className="text-lg text-muted-foreground">تومان</span></div>{oldPrice&&!selectedVariant?<p className="text-sm text-muted-foreground line-through">{formatEnglishPrice(oldPrice)} تومان</p>:null}</div><div className="flex items-center gap-3 sm:shrink-0"><span className="text-sm text-muted-foreground">تعداد:</span><QuantitySelector value={quantity} onChange={handleQuantityChange} disabled={!inStock} max={maxQuantity} numberLocale="en-US"/></div></div></div>
 <div className="space-y-2"><Button size="lg" className="h-12 w-full gap-2 rounded-xl bg-primary text-base hover:bg-primary/90 md:text-lg" disabled={!inStock} onClick={handleAddToCart}><ShoppingCart className="h-5 w-5"/><span>{inStock?"افزودن به سبد خرید":"ناموجود"}</span></Button><div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><Button asChild variant="outline" size="lg" className="h-11 w-full gap-2 rounded-xl"><a href={`tel:${supportPhone}`}><Phone className="h-4 w-4"/><span className="text-sm">درخواست مشاوره فنی</span></a></Button><Button asChild variant="outline" size="lg" className="h-11 w-full gap-2 rounded-xl"><a href={`tel:${supportPhone}`}><FileText className="h-4 w-4"/><span className="text-sm">استعلام قیمت عمده</span></a></Button></div></div><div className="grid grid-cols-3 gap-1 border-t border-border pt-3 sm:gap-3"><div className="flex flex-col items-center gap-2 p-2 text-center sm:p-3"><Truck className="h-6 w-6 text-primary"/><span className="text-xs text-muted-foreground">ارسال سریع</span></div><div className="flex flex-col items-center gap-2 p-2 text-center sm:p-3"><Shield className="h-6 w-6 text-primary"/><span className="text-xs text-muted-foreground">تضمین اصالت کالا</span></div><div className="flex flex-col items-center gap-2 p-2 text-center sm:p-3"><Headphones className="h-6 w-6 text-primary"/><span className="text-xs text-muted-foreground">پشتیبانی فنی تخصصی</span></div></div></div>
}
